daemon off;
user nginx;
worker_processes auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    '$status $body_bytes_sent "$http_referer" '
    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    server_tokens off;

    gzip on;
    gzip_comp_level 6;
    gzip_disable "msie6";
    gzip_min_length 1000;
    gzip_proxied any;
    gzip_types *;

    server {
        listen 80 default_server;

        error_page   404  /404.html;

        rewrite ^/assets/white_paper.* https://github.com/jibrelnetwork/white_paper permanent;

        location / {
            root /app;
            try_files $uri $uri/ =404;

            location ~* \.(?:manifest|appcache|html?|xml|json)$ {
                expires -1;
                add_header Cache-Control "public, must-revalidate";
            }

            location ~* ^/assets/img/[^/]+\.(?:jpg|jpeg|gif|png|ico|svg|webp)$ {
                expires 1y;
                add_header Cache-Control "public, immutable";
            }

            location ~* ^/assets/img/(?:blog|content|cover|partners)/[^/]+\.(?:jpg|jpeg|gif|png|ico|svg|webp)$ {
                expires 1d;
                add_header Cache-Control "public";
            }

            location ~* ^/assets/misc/[^/]+\.(?:jpg|jpeg|gif|png|ico|svg|webp)$ {
                expires 1d;
                add_header Cache-Control "public";
            }

            location ~* \.(?:css|js)$ {
                expires 1y;
                add_header Cache-Control "public, immutable";
            }

            location = /version.txt {
                expires -1;
            }
        }

        location /status {
            stub_status;
        }

        location /api/subscribe {
            if ($request_method = 'GET') {
                return 405;
            }

            add_header 'Access-Control-Allow-Origin' '$scheme://{{ .Env.HOSTNAME }}' always;
            add_header 'Access-Control-Allow-Methods' 'POST, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'DNT, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Range' always;
            add_header 'Access-Control-Expose-Headers' 'Content-Type' always;

            proxy_pass https://api2.autopilothq.com/v1/contact;
            proxy_set_header 'autopilotapikey' '{{ .Env.AUTOPILOT_API_KEY }}';
            proxy_hide_header 'Access-Control-Allow-Origin';
        }
    }
}
